### ISSUE TITLE
想要尝试解决下图出现的显示不美观现象（为字体大小做动画）

### ISSUE THREAD

**Issue by Dr-Bluemond** [Dr-Bluemond/HangGai#1]
<img width="47" alt="スクリーンショット 2021-06-15 午前0 26 43" src="https://user-images.githubusercontent.com/8200165/121926387-7ea97c80-cd70-11eb-8dad-81e74c6081dc.png">

method:
https://www.hackingwithswift.com/quick-start/swiftui/how-to-animate-the-size-of-text

**Comment by TakiVotoid** [comment]
ho～我之前也有查过这个。期待搞定！加油哦～
